
import __ASTRO_IMAGE_IMPORT_ZVkQG4 from "./arduino-automation-hub.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Farduino-automation-hub.md";
import __ASTRO_IMAGE_IMPORT_ZlguQd from "./blog-hero.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbaseline-rhythm.mdx";
import __ASTRO_IMAGE_IMPORT_kCCbo from "./bms-management.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Fbms-management.mdx";
import __ASTRO_IMAGE_IMPORT_Zht53N from "./energy-storage-materials.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Fenergy-storage-materials.md";
import __ASTRO_IMAGE_IMPORT_1iWRSp from "./fundamental-physics.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Ffundamental-physics.md";
import __ASTRO_IMAGE_IMPORT_Cw9dF from "./materials-characterization.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Fmaterials-characterization.md";
import __ASTRO_IMAGE_IMPORT_ZNV1S2 from "./mos2-cfo-pvp.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Fmos2-cfo-pvp.md";
import __ASTRO_IMAGE_IMPORT_ZJWzo5 from "./nioh2-synthesis.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Fnioh2-synthesis.md";
import __ASTRO_IMAGE_IMPORT_1dQb9N from "./sbs-process.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Fsbs-process.md";
import __ASTRO_IMAGE_IMPORT_1rChsu from "./smart-irrigation.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Fsmart-irrigation.md";
import __ASTRO_IMAGE_IMPORT_ZPw0qi from "./temporal-physics.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Ftemporal-physics.md";
import __ASTRO_IMAGE_IMPORT_szmkA from "./thermal-blanket.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Fthermal-blanket.md";
import __ASTRO_IMAGE_IMPORT_Z1FdLNc from "./u-microstrip.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Fu-microstrip.md";
export default new Map([["./arduino-automation-hub.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Farduino-automation-hub.md", __ASTRO_IMAGE_IMPORT_ZVkQG4], ["./blog-hero.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbaseline-rhythm.mdx", __ASTRO_IMAGE_IMPORT_ZlguQd], ["./bms-management.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Fbms-management.mdx", __ASTRO_IMAGE_IMPORT_kCCbo], ["./energy-storage-materials.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Fenergy-storage-materials.md", __ASTRO_IMAGE_IMPORT_Zht53N], ["./fundamental-physics.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Ffundamental-physics.md", __ASTRO_IMAGE_IMPORT_1iWRSp], ["./materials-characterization.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Fmaterials-characterization.md", __ASTRO_IMAGE_IMPORT_Cw9dF], ["./mos2-cfo-pvp.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Fmos2-cfo-pvp.md", __ASTRO_IMAGE_IMPORT_ZNV1S2], ["./nioh2-synthesis.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Fnioh2-synthesis.md", __ASTRO_IMAGE_IMPORT_ZJWzo5], ["./sbs-process.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Fsbs-process.md", __ASTRO_IMAGE_IMPORT_1dQb9N], ["./smart-irrigation.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Fsmart-irrigation.md", __ASTRO_IMAGE_IMPORT_1rChsu], ["./temporal-physics.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Ftemporal-physics.md", __ASTRO_IMAGE_IMPORT_ZPw0qi], ["./thermal-blanket.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Fthermal-blanket.md", __ASTRO_IMAGE_IMPORT_szmkA], ["./u-microstrip.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2Fu-microstrip.md", __ASTRO_IMAGE_IMPORT_Z1FdLNc]]);
		